## pandas

In [31]:
import pandas as pd

In [32]:
## series

import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print("series\n",series)
print(type(series))

series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [33]:
## series from dictionary

data = {'a':1, 'b':2,'c' :3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [34]:
data = [10,20,30] 
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [35]:
## dataframe
data ={
    'Name':['charan','kittu','vinay'],
    'age':['21','34','55'],
    'city':['hyd','Blr','dehli']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

     Name age   city
0  charan  21    hyd
1   kittu  34    Blr
2   vinay  55  dehli
<class 'pandas.DataFrame'>

In [36]:
df=pd.read_csv('dataa.csv')

print(df.head(5))

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [37]:
df.tail(5)

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [38]:
## acessing data 

df['Region']

0      East
1     North
2      East
3      East
4     North
5      West
6      East
7      West
8      West
9      West
10    North
11     West
12    South
13     East
14     West
15    North
16    South
17     West
18     West
19     East
20    South
21    South
22    North
23     West
24     East
25     West
26    North
27    North
28    North
29    South
30     West
31     West
32    South
33     East
34     West
35     West
36     East
37    North
38    South
39     West
40     East
41     East
42     West
43     East
44     East
45     West
46    South
47     West
48    North
49    North
Name: Region, dtype: str

In [39]:
df.loc(0)

In [40]:
df.iloc[0]

Date        2023-01-01
Category             A
Value             28.0
Product       Product1
Sales            754.0
Region            East
Name: 0, dtype: object

In [41]:
## accessing a spc element

df.at[1,'Date']

'2023-01-02'

In [42]:
## iat

df.iat[2,2]

np.float64(32.0)

In [ ]:
data

{'Name': ['charan', 'kittu', 'vinay'],
 'age': ['21', '34', '55'],
 'city': ['hyd', 'Blr', 'dehli']}

In [60]:

data['salary']=[39999,46666,34545]
data ## this is example not available 50 index data

{'Name': ['charan', 'kittu', 'vinay'],
 'age': ['21', '34', '55'],
 'city': ['hyd', 'Blr', 'dehli'],
 'salary': [39999, 46666, 34545]}

In [63]:
df.drop('salary',axis=1,inplace=True)

KeyError: "['salary'] not found in axis"

In [71]:
df['age']=df['age']+1
df

          Date Category  Value   Product  Sales Region  age
0   2023-01-01        A   28.0  Product1  754.0   East    2
1   2023-01-02        B   39.0  Product3  110.0  North    2
2   2023-01-03        C   32.0  Product2  398.0   East    2
3   2023-01-04        B    8.0  Product1  522.0   East    2
4   2023-01-05        B   26.0  Product3  869.0  North    2
5   2023-01-06        B   54.0  Product3  192.0   West    2
6   2023-01-07        A   16.0  Product1  936.0   East    2
7   2023-01-08        C   89.0  Product1  488.0   West    2
8   2023-01-09        C   37.0  Product3  772.0   West    2
9   2023-01-10        A   22.0  Product2  834.0   West    2
10  2023-01-11        B    7.0  Product1  842.0  North    2
11  2023-01-12        B   60.0  Product2    NaN   West    2
12  2023-01-13        A   70.0  Product3  628.0  South    2
13  2023-01-14        A   69.0  Product1  423.0   East    2
14  2023-01-15        A   47.0  Product2  893.0   West    2
15  2023-01-16        C    NaN  Product1  895.0  North    2
16  2023-01-17        C   93.0  Product2  511.0  South    2
17  2023-01-18        C    NaN  Product1  108.0   West    2
18  2023-01-19        A   31.0  Product2  578.0   West    2
19  2023-01-20        A   59.0  Product1  736.0   East    2
20  2023-01-21        C   82.0  Product3  606.0  South    2
21  2023-01-22        C   37.0  Product2  992.0  South    2
22  2023-01-23        B   62.0  Product3  942.0  North    2
23  2023-01-24        C   92.0  Product2  342.0   West    2
24  2023-01-25        A   24.0  Product2  458.0   East    2
25  2023-01-26        C   95.0  Product1  584.0   West    2
26  2023-01-27        C   71.0  Product2  619.0  North    2
27  2023-01-28        C   56.0  Product2  224.0  North    2
28  2023-01-29        B    NaN  Product3  617.0  North    2
29  2023-01-30        C   51.0  Product2  737.0  South    2
30  2023-01-31        B   50.0  Product3  735.0   West    2
31  2023-02-01        A   17.0  Product2  189.0   West    2
32  2023-02-02        B   63.0  Product3  338.0  South    2
33  2023-02-03        C   27.0  Product3    NaN   East    2
34  2023-02-04        C   70.0  Product3  669.0   West    2
35  2023-02-05        B   60.0  Product2    NaN   West    2
36  2023-02-06        C   36.0  Product3  177.0   East    2
37  2023-02-07        C    2.0  Product1    NaN  North    2
38  2023-02-08        C   94.0  Product1  408.0  South    2
39  2023-02-09        A   62.0  Product1  155.0   West    2
40  2023-02-10        B   15.0  Product1  578.0   East    2
41  2023-02-11        C   97.0  Product1  256.0   East    2
42  2023-02-12        A   93.0  Product3  164.0   West    2
43  2023-02-13        A   43.0  Product3  949.0   East    2
44  2023-02-14        A   96.0  Product3  830.0   East    2
45  2023-02-15        B   99.0  Product2  599.0   West    2
46  2023-02-16        B    6.0  Product1  938.0  South    2
47  2023-02-17        B   69.0  Product3  143.0   West    2
48  2023-02-18        C   65.0  Product3  182.0  North    2
49  2023-02-19        C   11.0  Product3  708.0  North    2

In [97]:
df.drop(2,inplace=True)

In [98]:
df

          Date Category  Value   Product  Sales Region  age
1   2023-01-02        B   39.0  Product3  110.0  North    2
3   2023-01-04        B    8.0  Product1  522.0   East    2
5   2023-01-06        B   54.0  Product3  192.0   West    2
6   2023-01-07        A   16.0  Product1  936.0   East    2
7   2023-01-08        C   89.0  Product1  488.0   West    2
8   2023-01-09        C   37.0  Product3  772.0   West    2
9   2023-01-10        A   22.0  Product2  834.0   West    2
10  2023-01-11        B    7.0  Product1  842.0  North    2
11  2023-01-12        B   60.0  Product2    NaN   West    2
12  2023-01-13        A   70.0  Product3  628.0  South    2
13  2023-01-14        A   69.0  Product1  423.0   East    2
14  2023-01-15        A   47.0  Product2  893.0   West    2
15  2023-01-16        C    NaN  Product1  895.0  North    2
16  2023-01-17        C   93.0  Product2  511.0  South    2
17  2023-01-18        C    NaN  Product1  108.0   West    2
18  2023-01-19        A   31.0  Product2  578.0   West    2
19  2023-01-20        A   59.0  Product1  736.0   East    2
20  2023-01-21        C   82.0  Product3  606.0  South    2
21  2023-01-22        C   37.0  Product2  992.0  South    2
22  2023-01-23        B   62.0  Product3  942.0  North    2
23  2023-01-24        C   92.0  Product2  342.0   West    2
24  2023-01-25        A   24.0  Product2  458.0   East    2
25  2023-01-26        C   95.0  Product1  584.0   West    2
26  2023-01-27        C   71.0  Product2  619.0  North    2
27  2023-01-28        C   56.0  Product2  224.0  North    2
28  2023-01-29        B    NaN  Product3  617.0  North    2
29  2023-01-30        C   51.0  Product2  737.0  South    2
30  2023-01-31        B   50.0  Product3  735.0   West    2
31  2023-02-01        A   17.0  Product2  189.0   West    2
32  2023-02-02        B   63.0  Product3  338.0  South    2
34  2023-02-04        C   70.0  Product3  669.0   West    2
35  2023-02-05        B   60.0  Product2    NaN   West    2
36  2023-02-06        C   36.0  Product3  177.0   East    2
37  2023-02-07        C    2.0  Product1    NaN  North    2
38  2023-02-08        C   94.0  Product1  408.0  South    2
39  2023-02-09        A   62.0  Product1  155.0   West    2
40  2023-02-10        B   15.0  Product1  578.0   East    2
41  2023-02-11        C   97.0  Product1  256.0   East    2
42  2023-02-12        A   93.0  Product3  164.0   West    2
43  2023-02-13        A   43.0  Product3  949.0   East    2
44  2023-02-14        A   96.0  Product3  830.0   East    2
45  2023-02-15        B   99.0  Product2  599.0   West    2
46  2023-02-16        B    6.0  Product1  938.0  South    2
47  2023-02-17        B   69.0  Product3  143.0   West    2
48  2023-02-18        C   65.0  Product3  182.0  North    2

In [100]:
df

          Date Category  Value   Product  Sales Region  age
1   2023-01-02        B   39.0  Product3  110.0  North    2
3   2023-01-04        B    8.0  Product1  522.0   East    2
5   2023-01-06        B   54.0  Product3  192.0   West    2
6   2023-01-07        A   16.0  Product1  936.0   East    2
7   2023-01-08        C   89.0  Product1  488.0   West    2
8   2023-01-09        C   37.0  Product3  772.0   West    2
9   2023-01-10        A   22.0  Product2  834.0   West    2
10  2023-01-11        B    7.0  Product1  842.0  North    2
11  2023-01-12        B   60.0  Product2    NaN   West    2
12  2023-01-13        A   70.0  Product3  628.0  South    2
13  2023-01-14        A   69.0  Product1  423.0   East    2
14  2023-01-15        A   47.0  Product2  893.0   West    2
15  2023-01-16        C    NaN  Product1  895.0  North    2
16  2023-01-17        C   93.0  Product2  511.0  South    2
17  2023-01-18        C    NaN  Product1  108.0   West    2
18  2023-01-19        A   31.0  Product2  578.0   West    2
19  2023-01-20        A   59.0  Product1  736.0   East    2
20  2023-01-21        C   82.0  Product3  606.0  South    2
21  2023-01-22        C   37.0  Product2  992.0  South    2
22  2023-01-23        B   62.0  Product3  942.0  North    2
23  2023-01-24        C   92.0  Product2  342.0   West    2
24  2023-01-25        A   24.0  Product2  458.0   East    2
25  2023-01-26        C   95.0  Product1  584.0   West    2
26  2023-01-27        C   71.0  Product2  619.0  North    2
27  2023-01-28        C   56.0  Product2  224.0  North    2
28  2023-01-29        B    NaN  Product3  617.0  North    2
29  2023-01-30        C   51.0  Product2  737.0  South    2
30  2023-01-31        B   50.0  Product3  735.0   West    2
31  2023-02-01        A   17.0  Product2  189.0   West    2
32  2023-02-02        B   63.0  Product3  338.0  South    2
34  2023-02-04        C   70.0  Product3  669.0   West    2
35  2023-02-05        B   60.0  Product2    NaN   West    2
36  2023-02-06        C   36.0  Product3  177.0   East    2
37  2023-02-07        C    2.0  Product1    NaN  North    2
38  2023-02-08        C   94.0  Product1  408.0  South    2
39  2023-02-09        A   62.0  Product1  155.0   West    2
40  2023-02-10        B   15.0  Product1  578.0   East    2
41  2023-02-11        C   97.0  Product1  256.0   East    2
42  2023-02-12        A   93.0  Product3  164.0   West    2
43  2023-02-13        A   43.0  Product3  949.0   East    2
44  2023-02-14        A   96.0  Product3  830.0   East    2
45  2023-02-15        B   99.0  Product2  599.0   West    2
46  2023-02-16        B    6.0  Product1  938.0  South    2
47  2023-02-17        B   69.0  Product3  143.0   West    2
48  2023-02-18        C   65.0  Product3  182.0  North    2

In [101]:
df.describe()

           Value       Sales   age
count  42.000000   42.000000  45.0
mean   54.952381  545.214286   2.0
std    29.007949  279.508675   0.0
min     2.000000  108.000000   2.0
25%    36.250000  276.500000   2.0
50%    59.500000  581.000000   2.0
75%    70.750000  763.250000   2.0
max    99.000000  992.000000   2.0